services:
  mongodb:
    image: mongo:latest
    container_name: spider_crawling_db
    profiles: [ "prod" ]
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - ./db-data/:/data/db
  mongodb_test:
    image: mongo:latest
    container_name: spider_crawling_db_test
    profiles: [ "test" ]
    env_file:
      - .env.test
    ports:
      - "27018:27017"
    volumes:
      - ./db-data-test/:/data/db